"use strict";

(() => {
  const definitions = globalThis.DRAGON_HUNTER_DEFINITIONS;
  if (!definitions) {
    throw new Error("DRAGON_HUNTER_DEFINITIONS must be loaded before state helpers");
  }

  const { TILE, WORLD_SCALE } = definitions;

  function createInitialState() {
    return {
      keys: new Set(),
      virtualKeys: new Set(),
      map: [],
      monsters: [],
      sparks: [],
      slashes: [],
      rings: [],
      telegraphs: [],
      floaters: [],
      particles: [],
      projectiles: [],
      npcs: [],
      chests: new Set(),
      discoveries: new Set(),
      arrivedSafeBases: new Set(["village"]),
      spawnedBoss: false,
      bossDefeated: false,
      spawnedGuardian: false,
      guardianDefeated: false,
      spawnedWarden: false,
      wardenDefeated: false,
      spawnedAshKnight: false,
      ashKnightDefeated: false,
      spawnedMoonGatekeeper: false,
      moonGatekeeperDefeated: false,
      spawnedArchiveWarden: false,
      archiveWardenDefeated: false,
      spawnedSmugglerCaptain: false,
      smugglerCaptainDefeated: false,
      spawnedRegenSentinel: false,
      regenSentinelDefeated: false,
      spawnedMistKeeper: false,
      mistKeeperDefeated: false,
      spawnedCryptWarden: false,
      cryptWardenDefeated: false,
      spawnedFrostGolem: false,
      frostGolemDefeated: false,
      spawnedStormRoc: false,
      stormRocDefeated: false,
      spawnedTowerWarden: false,
      towerWardenDefeated: false,
      spawnedFrostDragon: false,
      frostDragonDefeated: false,
      spawnedSolarWarden: false,
      solarWardenDefeated: false,
      spawnedSuncrestChampion: false,
      suncrestChampionDefeated: false,
      spawnedSunspireKeeper: false,
      sunspireKeeperDefeated: false,
      spawnedEmberDragon: false,
      emberDragonDefeated: false,
      spawnedEclipseDragon: false,
      eclipseDragonDefeated: false,
      spawnedVoidDragon: false,
      voidDragonDefeated: false,
      spawnedObsidianGolem: false,
      obsidianGolemDefeated: false,
      elderReported: false,
      chapter2Victory: false,
      chapter2Reported: false,
      chapter3Victory: false,
      chapter3Reported: false,
      chapter4Victory: false,
      chapter4Reported: false,
      chapter5Victory: false,
      chapter5Reported: false,
      clearPanelOpen: false,
      spawnTimer: 600,
      message: "",
      messageUntil: 0,
      last: performance.now(),
      shake: 0,
      searchCooldown: 0,
      healCooldown: 0,
      townGateOpen: false,
      townGateHold: 0,
      statsFlip: false,
      statsPage: 0,
      infoPanel: null,
      inventoryOpen: false,
      worldMapOpen: false,
      inventoryTab: "items",
      inventoryIndex: 0,
      shopOpen: false,
      shopTitle: "",
      shopRows: [],
      shopIndex: 0,
      gameOver: false,
      victory: false,
      pointerMove: null,
      regionSpawnTimer: 0,
      lastRegion: "grassland",
    };
  }

  function createInitialPlayer() {
    return {
      x: 10 * TILE,
      y: 48 * TILE,
      w: 10 * WORLD_SCALE,
      h: 12 * WORLD_SCALE,
      dir: "down",
      hp: 26,
      hpMax: 26,
      level: 1,
      strength: 9,
      resilience: 2,
      xp: 0,
      xpNext: 34,
      gold: 18,
      weapon: 0,
      armor: 0,
      shield: 0,
      shieldRune: "",
      ownedWeapons: [0],
      ownedArmors: [0],
      ownedShields: [0],
      ownedAccessories: [],
      equippedAccessory: "",
      equippedAccessories: [],
      potions: 2,
      tonics: 0,
      bombs: 1,
      wards: 0,
      elixirs: 0,
      warps: 0,
      selectedItem: "potion",
      quickItems: ["potion", "bomb", "ward"],
      activeQuickSlot: 0,
      scales: 0,
      sealCrest: false,
      hunterCharm: false,
      regenCharm: false,
      greaterRegenCharm: false,
      trailCharm: false,
      aegisCharm: false,
      mineCharm: false,
      mistCharm: false,
      eclipseCharm: false,
      voidCharm: false,
      obsidianCharm: false,
      deepLampCharm: false,
      galeCharm: false,
      frostCharm: false,
      skyCharm: false,
      horizonCharm: false,
      prismLensCharm: false,
      duelistCharm: false,
      expeditionBlessing: "",
      expeditionBlessingTime: 0,
      stamina: 100,
      staminaMax: 100,
      attackCooldown: 0,
      dashCooldown: 0,
      invuln: 0,
      guard: 0,
      slow: 0,
      burn: 0,
      burnTick: 0,
      combo: 0,
      comboTimer: 0,
      speed: 66 * WORLD_SCALE,
      step: 0,
    };
  }

  globalThis.DRAGON_HUNTER_STATE = {
    createInitialState,
    createInitialPlayer,
  };
})();
